security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
 

    
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
    
    providers:
        in_memory:
            memory: 
        fos_userbundle:
            id: fos_user.user_provider.username


    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false
            
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                default_target_path: /accueilEtudiant
            logout:       
                path: /logout
                target: /login
                invalidate_session: false
            anonymous:    true
            
            
        default:
            anonymous: ~

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        
        - { path: ^/profile/edit, role: IS_AUTHENTICATED_REMEMBERED }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        
        - { path: ^/administration, role: ROLE_ADMIN }
        
       # a ajouter plus tard
        # - { path: ^/accueilAdmin, role: ROLE_ADMIN } #}
        # - { path: ^/suiviEtudiant, role: ROLE_ADMIN } #}
        # - { path: ^/suiviStages, role: ROLE_ADMIN } #}
      
        #coté admin
        - { path: ^/accueilAdmin, role: IS_AUTHENTICATED_REMEMBERED }
        - { path: ^/suiviEtudiant, role: IS_AUTHENTICATED_REMEMBERED } 
        - { path: ^/suiviStages, role: IS_AUTHENTICATED_REMEMBERED } 

        #coté étudiant
        - { path: ^/accueilEtudiant, role: IS_AUTHENTICATED_REMEMBERED }
        - { path: ^/entreprise/ajouter, role: IS_AUTHENTICATED_REMEMBERED }
        - { path: ^/tuteur/ajouter/id, role: IS_AUTHENTICATED_REMEMBERED }
        - { path: ^/stage/ajouter1, role: IS_AUTHENTICATED_REMEMBERED }
        - { path: ^/stage/ajouter2, role: IS_AUTHENTICATED_REMEMBERED }
        - { path: ^/stage/id, role: IS_AUTHENTICATED_REMEMBERED }
        - { path: ^/entreprise/rechercher, role: IS_AUTHENTICATED_REMEMBERED }
        - { path: ^/entreprise/id, role: IS_AUTHENTICATED_REMEMBERED }
        - { path: ^/entreprise/resultat, role: IS_AUTHENTICATED_REMEMBERED }
