security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
 

    
    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_ETU]
        ROLE_SUPER_ADMIN: ROLE_ADMIN
    
    providers:
        in_memory:
            memory: 
        fos_userbundle:
            id: fos_user.user_provider.username


    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false
            
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                success_handler: redirect.after.login
                
            logout:       
                path: /logout
                target: /login
                invalidate_session: false
            anonymous:    true
            
            
        default:
            anonymous: ~

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login/nonValide, role: IS_AUTHENTICATED_ANONYMOUSLY }
        
        #coté admin
        - { path: ^/administration, role: ROLE_ADMIN }
      
        #coté étudiant
        - { path: ^/, role: ROLE_ETU }
