# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    parameter_name: value

services:
    btsappli_user.registration.form.type:
        class: btsappli\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: btsappli_user_registration }
            
    btsappli_user.profile.for.type:
        class: btsappli\UserBundle\Form\Type\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: btsappli_user_profile }