btsappli_CCF_editionChoixTypeCCF:
    path:   /administration/editer/choisirTypeCCF
    defaults: { _controller: btsappliCCFBundle:CCF:editionChoixTypeCCF }

btsappli_CCF_ajoutEcrit:
    path:   /administration/editer/ecrit
    defaults: { _controller: btsappliCCFBundle:CCF:ajoutEcrit }

btsappli_CCF_ajoutOral:
    path:   /administration/editer/oral
    defaults: { _controller: btsappliCCFBundle:CCF:ajoutOral }


btsappli_CCF_planningChoixTypeCCF:
    path:   /administration/planning/choisirTypeCCF
    defaults: { _controller: btsappliCCFBundle:CCF:planningChoixTypeCCF }

btsappli_CCF_planningOraux:
    path:   /administration/planningOraux
    defaults: { _controller: btsappliCCFBundle:CCF:planningOraux }

btsappli_CCF_planningOrauxPromo:
    path:   /administration/planningOraux/{idPromo}
    defaults: { _controller: btsappliCCFBundle:CCF:planningOrauxPromo }
    requirements:
        idPromo:   \d+

btsappli_CCF_planningOrauxMatiere:
    path:   /administration/planningOraux/{matiere}
    defaults: { _controller: btsappliCCFBundle:CCF:planningOrauxMatiere }

btsappli_CCF_planningEcrits:
    path:   /administration/planningEcrits
    defaults: { _controller: btsappliCCFBundle:CCF:planningEcrits }