<?php

namespace btsappli\StagesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TuteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TuteurRepository extends EntityRepository
{
    public function getTuteursDUneEntreprise($id)
	{
 
		$qb = $this->createQueryBuilder('t');
 
		$qb->where('t.entreprise = :id')
			  ->setParameter('id', $id)
			  	->orderBy('t.nom', 'ASC');
 
		return $qb;
	}
}
