<?php

namespace btsappli\CCFBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EcritRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EcritRepository extends EntityRepository
{

}
