<?php

namespace btsappli\CCFBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OralRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OralRepository extends EntityRepository
{
}
