btsappli_stages_entrepriseFormulaire:
    path:     /entreprise/ajouter
    defaults: { _controller: btsappliStagesBundle:Stages:ajoutEntreprise }

btsappli_stages_tuteurFormulaire:
    path:     /tuteur/ajouter/{id}
    defaults: { _controller: btsappliStagesBundle:Stages:ajoutTuteur }
    requirements:
        id:   \d+

btsappli_stages_ajoutStage:
    path:     /stage/ajouter1
    defaults: { _controller: btsappliStagesBundle:Stages:ajoutStage }

btsappli_stages_stageFormulaireTut:
    path:     /stage/ajouter2
    defaults: { _controller: btsappliStagesBundle:Stages:ajoutStageTut }

btsappli_stages_voirStage:
    path:     /stage/{id}
    defaults: { _controller: btsappliStagesBundle:Stages:voirStage }
    requirements:
        id:   \d+

btsappli_stages_rechercheEntreprise:
    path:     /entreprise/rechercher
    defaults: { _controller: btsappliStagesBundle:Stages:rechercherEntreprise }

btsappli_stages_voirEntreprise:
    path:     /entreprise/{id}
    defaults: { _controller: btsappliStagesBundle:Stages:voirEntreprise }
    requirements:
        id:   \d+
        
btsappli_stages_resultatRecherche:
    path:     /entreprise/resultat
    defaults: { _controller: btsappliStagesBundle:Stages:resultatRecherche }
    requirements:
        _method: POST
    