btsappli_utilisateurs_accueilEtu:
    path:     /accueilEtudiant
    defaults: { _controller: btsappliUserBundle:User:accueilEtudiant }

btsappli_utilisateurs_accueilAdmin:
    path:     /administration/accueil
    defaults: { _controller: btsappliUserBundle:User:accueilAdmin }

#************************************************************************************************************
    
btsappli_utilisateurs_suiviEtudiant:
    path:   /administration/suiviEtudiants
    defaults: { _controller: btsappliUserBundle:User:suiviEtudiant }
    
btsappli_utilisateurs_setPromo:
    path:   /administration/suiviEtudiant/{id}/{idPromo}
    defaults: { _controller: btsappliUserBundle:User:setPromo }
    requirements:
        id:      \d+
        idPromo: \d+

btsappli_utilisateurs_suiviEtudiantFiltrer:
    path:   /administration/suiviEtudiantFiltrer/{idPromo}
    defaults: { _controller: btsappliUserBundle:User:suiviEtudiantFiltrer }
    requirements:
        idPromo:   \d+
    
#************************************************************************************************************

btsappli_utilisateurs_ajoutPromo:
    path:   /administration/ajouterPromo
    defaults: { _controller: btsappliUserBundle:User:ajoutPromo }
    
#************************************************************************************************************

btsappli_utilisateurs_suiviStages:
    path:   /administration/suiviStages
    defaults: { _controller: btsappliUserBundle:User:suiviStages }
    
btsappli_utilisateurs_voirStageEtu:
    path:   /administration/voirStageEtu/{id}
    defaults: { _controller: btsappliUserBundle:User:voirStageEtu }
    requirements:
        id:   \d+
    
btsappli_utilisateurs_setEtatConv:
    path:   /administration/voirStageEtu/{id}/{etatConv}
    defaults: { _controller: btsappliUserBundle:User:setEtatConv }
    requirements:
        id:       \d+
        etatConv: \d+
    
btsappli_utilisateurs_suiviStagesFiltrerPromo:
    path:   /administration/suiviStagesFiltrerPromo/{idPromo}
    defaults: { _controller: btsappliUserBundle:User:suiviStagesFiltrerPromo }
    requirements:
        idPromo:   \d+

btsappli_utilisateurs_suiviStagesFiltrerConventionValidee:
    path:   /administration/suiviStagesFiltrerConventionValidee
    defaults: { _controller: btsappliUserBundle:User:suiviStagesFiltrerConventionValidee }

btsappli_utilisateurs_suiviStagesFiltrerConventionNonValidee:
    path:   /administration/suiviStagesFiltrerConventionNonValidee
    defaults: { _controller: btsappliUserBundle:User:suiviStagesFiltrerConventionNonValidee }

btsappli_utilisateurs_suiviStagesFiltrerConventionSignee:
    path:   /administration/suiviStagesFiltrerConventionSignee
    defaults: { _controller: btsappliUserBundle:User:suiviStagesFiltrerConventionSignee }

btsappli_utilisateurs_suiviStagesFiltrerPasStage:
    path:   /administration/suiviStagesFiltrerPasStage
    defaults: { _controller: btsappliUserBundle:User:suiviStagesFiltrerPasStage }

btsappli_utilisateurs_supprimerStage:
    path:   /administration/suiviStages/supprimerStage/{id}
    defaults: { _controller: btsappliUserBundle:User:supprimerStage }
    requirements:
        id:   \d+
    
btsappli_utilisateurs_supprimerStageValidation:
    path:   /administration/suiviStages/supprimerStageValidation/{id}
    defaults: { _controller: btsappliUserBundle:User:supprimerStageValidation }
    requirements:
        id:   \d+

btsappli_utilisateurs_ReinitialiserStages:
    path:   /administration/suiviStages/ReinitialiserStages
    defaults: { _controller: btsappliUserBundle:User:reinitialiserStages }
    
btsappli_utilisateurs_ReinitStagesValidation:
    path:   /administration/suiviStages/ReinitStagesValidation
    defaults: { _controller: btsappliUserBundle:User:reinitStagesValidation }

#************************************************************************************************************

btsappli_utilisateurs_validerInscriptions:
    path:   /administration/validationsUser
    defaults: { _controller: btsappliUserBundle:User:validationsUser }
    
btsappli_utilisateurs_setPromoInscription:
    path:   /administration/validationsUser/setPromo/{id}/{idPromo}
    defaults: { _controller: btsappliUserBundle:User:setPromoInscription }
    requirements:
        id:      \d+
        idPromo: \d+
    
btsappli_utilisateurs_supprInscriptions:
    path:   /administration/validationsUser/suppr/{id}
    defaults: { _controller: btsappliUserBundle:User:supprimerValidation }
    requirements:
        id:   \d+
    
btsappli_utilisateurs_acceptInscriptions:
    path:   /administration/validationsUser/accepter/{id}
    defaults: { _controller: btsappliUserBundle:User:accepterValidation }
    requirements:
        id:   \d+
    
