btsappli_utilisateurs_accueilEtu:
    path:     /accueilEtu
    defaults: { _controller: btsappliUserBundle:User:menuEtu }

btsappli_utilisateurs_accueilAdmin:
    path:     /accueilAdmin
    defaults: { _controller: btsappliUserBundle:User:menuAdmin }