btsappli_utilisateurs_accueilEtu:
    path:     /accueilEtudiant
    defaults: { _controller: btsappliUserBundle:User:accueilEtudiant }

btsappli_utilisateurs_accueilAdmin:
    path:     /accueilAdmin
    defaults: { _controller: btsappliUserBundle:User:accueilAdmin }

#************************************************************************************************************
    
btsappli_utilisateurs_suiviEtudiant:
    path:   /suiviEtudiant
    defaults: { _controller: btsappliUserBundle:User:suiviEtudiant }
    
btsappli_utilisateurs_setPromo:
    path:   /suiviEtudiant/{id}/{idPromo}
    defaults: { _controller: btsappliUserBundle:User:setPromo }

btsappli_utilisateurs_suiviEtudiantFiltrer:
    path:   /suiviEtudiantFiltrer/{idPromo}
    defaults: { _controller: btsappliUserBundle:User:suiviEtudiantFiltrer }
    
#************************************************************************************************************

btsappli_utilisateurs_suiviStages:
    path:   /suiviStages
    defaults: { _controller: btsappliUserBundle:User:suiviStages }
    
btsappli_utilisateurs_suiviStagesFiltrerPromo:
    path:   /suiviStagesFiltrerPromo
    defaults: { _controller: btsappliUserBundle:User:suiviStagesFiltrerPromo }

btsappli_utilisateurs_suiviStagesFiltrerConventionValidee:
    path:   /suiviStagesFiltrerConventionValidee
    defaults: { _controller: btsappliUserBundle:User:suiviStagesFiltrerConventionValidee }

btsappli_utilisateurs_suiviStagesFiltrerConventionNonValidee:
    path:   /suiviStagesFiltrerConventionNonValidee
    defaults: { _controller: btsappliUserBundle:User:suiviStagesFiltrerConventionNonValidee }

btsappli_utilisateurs_suiviStagesFiltrerConventionSignee:
    path:   /suiviStagesFiltrerConventionSignee
    defaults: { _controller: btsappliUserBundle:User:suiviStagesFiltrerConventionSignee }

btsappli_utilisateurs_suiviStagesFiltrerPasStage:
    path:   /suiviStagesFiltrerPasStage
    defaults: { _controller: btsappliUserBundle:User:suiviStagesFiltrerPasStage }

btsappli_utilisateurs_supprimerStage:
    path:   /suiviStages/supprimerStage/{id}
    defaults: { _controller: btsappliUserBundle:User:supprimerStage }
    
btsappli_utilisateurs_supprimerStageValidation:
    path:   /suiviStages/supprimerStageValidation/{id}
    defaults: { _controller: btsappliUserBundle:User:supprimerStageValidation }

#************************************************************************************************************

btsappli_utilisateurs_validerInscriptions:
    path:   /validationsUser
    defaults: { _controller: btsappliUserBundle:User:validationsUser }
    
btsappli_utilisateurs_supprInscriptions:
    path:   /validationsUser/supprimer/{id}
    defaults: { _controller: btsappliUserBundle:User:supprimerValidation }
    requirements:
        id:   \d+
    
btsappli_utilisateurs_acceptInscriptions:
    path:   /validationsUser/accepter/{id}
    defaults: { _controller: btsappliUserBundle:User:accepterValidation }
    requirements:
        id:   \d+
    
